### PR TITLE
Compile riot tags in asset pipeline

### PR DESCRIPTION
**Pull request by marcioj**
This PR make possible files within `app/assets/javascripts` ending with `.tag` be compiled using the riotjs compiler. So given a file `message.tag` with the contents:

```
<message>
  <p>{ begin } { end }</p>

  this.begin = 'Hello';
  this.end = "world";
</message>
```

The user will be served with a file `message.js` with the contents:

```
riot.tag('message', '<p>{ begin } { end }</p>', function(opts) {

  this.begin = 'Hello';
  this.end = "world";

});
```

I also included a test using rspec, let me know if you have other test framework of preference :).
To be able to use the compiler we need to use node.js, so It becomes an external dependency. 
I can update the README with instructions of how to install node and use these features, just let me know if it's good to go.

### CODE REVIEW

**Comment by marcioj** [comment]
I updated the code to use rails `escape_javascript ,` which is more safe to use instead my previous implementation. And extracted the riot compiler code to a class called `Riot::Rails::JavascriptCompiler`.
I think it's now ready for some :eyes:

**Comment by blahutka** [comment]
+1

**Comment by adambutler** [comment]
@marcioj Sorry this seemed to have disappeared from my to-do list by accident.

:+1: It all looks good to me - I've added you as a contributor but please keep any further features as pull requests.

**Comment by blahutka** [comment]
Hi @marcioj is it possible to implement parsing by erb to the .tag files as well.  eg. `template_fle.tag.erb`

**Comment by marcioj** [comment]
No problem @adambutler, thanks for adding me as contributor. I added a section to the readme explaining how to use this new feature. Let me know if it's good enough. If so I can merge this PR.

@blahutka I tested this in a local project and renaming the file to `template_fle.tag.erb` worked. Thanks for the rails asset pipeline :smile:

**Comment by blahutka** [comment]
@marcioj I had to do something wrong, it works now for me too. Thank you.

**Comment by adambutler** [comment]
@marcioj I'll have time to test it over the weekend but if your confident that it's well tested feel free to :shipit: :+1:

**Comment by lifeiscontent** [comment]
@marcioj any chance of extending this further so you can serve the rendered HTML on the request?

**Comment by marcioj** [comment]
Hi @lifeiscontent I'm unsure if I get what you want. Do you want to make the tags be processed in `app/view/*` directory and be served by a controller. Like the example below?

**config/routes.rb**

``` ruby
get :message_tag => 'tags#message'
```

**app/controllers/tags_controller.rb**

``` ruby
class TagsController
  def message
  end
end
```

**app/views/tags/message.tag**

``` jsx
<message>
  <p>{ begin } { end }</p>

  this.begin = 'Hello';
  this.end = "world";
</message>
```

So requesting `/tags/message` should return

``` js
riot.tag('message', '<p>{ begin } { end }</p>', function(opts) {

  this.begin = 'Hello';
  this.end = "world";

});
```

**Comment by lifeiscontent** [comment]
@marcioj https://www.youtube.com/watch?v=VKTWdaupft0&feature=youtu.be&t=14m28s

long story short. I'd like to do something like

**app/views/tags/message.html.erb**

``` erb
<%= render_tag 'message', {begin: 'Hello', end: 'world'} %>
```

and then, the render_tag would just output the HTML and add the JS to rehydrate the views as needed

**Comment by marcioj** [comment]
Hi @lifeiscontent, I was giving a look in your suggestion and I believe this isn't possible right now. I opened an issue in riot/riot#949 to track it down.

**Comment by lifeiscontent** [comment]
Cool, thanks :) :+1:

**Pull request merged**
